apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/name: nginx
  name: antaeus-api
  namespace: antaeus
spec:
  rules:
  - host: DOMAIN_PLACEHOLDER
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 8080
  tls:
  - hosts:
    - DOMAIN_PLACEHOLDER
    secretName: TLS_SECRET_NAME

