apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    toleration: sre-team
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: Payments
  name: payments-api
  namespace: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: demo
      app.kubernetes.io/managed-by: Pleo
      app.kubernetes.io/name: Payments
      app.kubernetes.io/part-of: tinjis
      app.kubernetes.io/version: demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: demo
        app.kubernetes.io/managed-by: Pleo
        app.kubernetes.io/name: Payments
        app.kubernetes.io/part-of: tinjis
        app.kubernetes.io/version: demo
    spec:
      containers:
      - image: payments
        name: api
        env:
        - name:  RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails
              key: MASTER_KEY
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: api
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 3000
          name: api
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: api
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
      terminationGracePeriodSeconds: 5
