apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: antaeus
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: api
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: demo
    app.kubernetes.io/name: Antaeus
    app.kubernetes.io/part-of: tinjis
  type: ClusterIP
