---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: Pleo
    app.kubernetes.io/part-of: tinjis
  name: antaeus
---
apiVersion: v1
data:
  ENDPOINT: http://api.payments.svc.cluster.local:8080/payments
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Pleo
    app.kubernetes.io/part-of: tinjis
  name: payments
  namespace: antaeus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: antaeus-api
  namespace: antaeus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: demo
      app.kubernetes.io/managed-by: Pleo
      app.kubernetes.io/name: Antaeus
      app.kubernetes.io/part-of: tinjis
      app.kubernetes.io/version: demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: demo
        app.kubernetes.io/managed-by: Pleo
        app.kubernetes.io/name: Antaeus
        app.kubernetes.io/part-of: tinjis
        app.kubernetes.io/version: demo
    spec:
      containers:
      - image: rickbgs/tinjis-antaeus:demo
        name: api
        env:
        - name: JVM_OPTS
          value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Xms2048M
        - name:  PAYMENT_PROVIDER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: payments
              key: ENDPOINT
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /rest/health
            port: api
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 8000
          name: api
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /rest/health
            port: api
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          # QoS Class: Burstable
          limits:
            cpu: 500m
          requests:
            cpu: 100m
            memory: 3072Mi
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Pleo
    app.kubernetes.io/part-of: tinjis
  name: api
  namespace: antaeus
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: api
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: demo
    app.kubernetes.io/name: Antaeus
    app.kubernetes.io/part-of: tinjis
  type: LoadBalancer
# ---
# apiVersion: policy/v1beta1
# kind: PodDisruptionBudget
# metadata:
#   labels:
#     app.kubernetes.io/managed-by: Pleo
#     app.kubernetes.io/part-of: tinjis
#   name: api
#   namespace: antaeus
# spec:
#   maxUnavailable: 1
#   selector:
#     matchLabels:
#       app.kubernetes.io/component: api
#       app.kubernetes.io/instance: demo
#       app.kubernetes.io/name: Antaeus
#       app.kubernetes.io/part-of: tinjis
