---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: Pleo
    app.kubernetes.io/part-of: tinjis
  name: payments
---
# kubectl create secret generic rails --from-literal=MASTER_KEY=6ce3e113e76b22d90c9e73980f89165f --dry-run --namespace payments -o yaml  |
# kubectl label -f - --dry-run --local -o yaml \
#     app.kubernetes.io/managed-by=Pleo \
#     app.kubernetes.io/part-of=tinjis
apiVersion: v1
data:
  MASTER_KEY: NmNlM2UxMTNlNzZiMjJkOTBjOWU3Mzk4MGY4OTE2NWY=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: Pleo
    app.kubernetes.io/part-of: tinjis
  name: rails
  namespace: payments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Pleo
    app.kubernetes.io/part-of: tinjis
  name: payments-api
  namespace: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: demo
      app.kubernetes.io/managed-by: Pleo
      app.kubernetes.io/name: Payments
      app.kubernetes.io/part-of: tinjis
      app.kubernetes.io/version: demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: demo
        app.kubernetes.io/managed-by: Pleo
        app.kubernetes.io/name: Payments
        app.kubernetes.io/part-of: tinjis
        app.kubernetes.io/version: demo
    spec:
      containers:
      - image: rickbgs/tinjis-payments:demo
        name: api
        env:
        - name:  RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails
              key: MASTER_KEY
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: api
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 3000
          name: api
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: api
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          # QoS Class: Guaranteed
          limits:
            cpu: 100m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 1024Mi
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Pleo
    app.kubernetes.io/part-of: tinjis
  name: api
  namespace: payments
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: api
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: demo
    app.kubernetes.io/name: Payments
    app.kubernetes.io/part-of: tinjis
  type: ClusterIP
