- op: add
  path: /spec/template/spec/affinity
  value: {}
- op: add
  path: /spec/template/spec/affinity/nodeAffinity
  value:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.kubernetes.io/name
          operator: In
          values:
          - Payments
